# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &defaults
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  customer_email: <%= ENV["CUSTOMER_EMAIL"] %>
  customer_password: <%= ENV["CUSTOMER_PASSWORD"] %>
  coach_email: <%= ENV["COACH_EMAIL"] %>
  coach_password: <%= ENV["COACH_PASSWORD"] %>
  stadium_email: <%= ENV["STADIUM_EMAIL"] %>
  stadium_password: <%= ENV["STADIUM_PASSWORD"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  merchant_id: 123123123
  merchant_key: 123123123
  

development:
  <<: *defaults
  email_provider_username: <%= ENV["YANDEX_NAME"] %>
  email_provider_apikey: <%= ENV["YANDEX_PASSWORD"] %> 
  domain_name: tennis-rails.dev
  secret_key_base: e5f5056665d8d0bad1a25fab28564a1edd29822af26d3d6a2adb1c424a3bec39b3904596cc014d973b052b8dd4ccb6c95c84c721c11b7fcf22a9e6ebf96ee4e6
  payment_result_url: http://localhost/dashboard/payments/success/

test:
  domain_name: example.com 
  secret_key_base: 85153985f188d751706c2b07da3e610f7be66a69e967557cd5acaacb3b0164f1deacb035ecd431f231a89b1cd3498e923ad5bb6b4713f8c8ed66865e8c539b43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults
  email_provider_username: <%= ENV["YANDEX_NAME"] %>
  email_provider_apikey: <%= ENV["YANDEX_PASSWORD"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  payment_result_url: 123123123
